version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: splitwise_postgres
    environment:
      POSTGRES_DB: splitwise_db
      POSTGRES_USER: splitwise_user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - splitwise_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: splitwise_backend
    environment:
      DATABASE_URL: postgresql://splitwise_user:password@postgres:5432/splitwise_db
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
    networks:
      - splitwise_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: splitwise_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - splitwise_network

volumes:
  postgres_data:

networks:
  splitwise_network:
    driver: bridge
